version: 'Compose specification'

services:
  app:
    container_name: express-app
    image: app:latest
    build: .
    environment:
      NODE_ENV: development
      DB_HOST: rdb
    ports:
      - 4000:4000
    depends_on:
      - rdb

  rdb:
    container_name: express-rdb
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_USER=svc_express
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_express
      - TZ=Asia/Seoul
    ports:
      - '3306:3306'
    volumes:
      - './rdb:/var/lib/mysql'
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
